const letterPages = [
  {
    title: "Page 1",
    text: "My Dear Best Friend,\n\nHappy Birthday.\n\nCongratulations. You survived another year of my terrible jokes, my worse puns, and at least three separate attempts by me to explain manufacturing processes to you in far more detail than anyone asked for. That alone deserves a cake, possibly two.\n\nAlright. Joke's out of the way. Let me be serious for a bit, because apparently that's what birthday letters require, and because you're the one who actually writes proper letters, not me. You sit down, think about a person properly, and put it on paper, while the rest of us settle for a message and a cake. So this year I'm returning the favour. Badly, probably. But trying.\n\nI started this letter a few times and deleted most of it. Turns out summing up a year of someone quietly becoming one of your closest friends is harder than it sounds, and I talk for a living, more or less. Ask anyone in the office. I can turn a five-minute update into a twenty-minute one without even trying. But this one kept getting stuck. I'd write a paragraph, read it back, decide it sounded like it was written by someone other than me, and start again. Happened more times than I'm willing to admit in writing, which is ironic, because I'm currently admitting it in writing.\n\nSo here it is anyway. No hidden agenda. No dramatic twist waiting on the last page. Just one friend trying to tell another how glad he is that life, for no particular reason, decided to make their paths cross, and then, for even less reason, kept them crossed this long.\n\nSo here is where it started."
  },
  {
    title: "Page 2",
    text: "I don't actually remember where I found your résumé. Genuinely don't. It was probably one among hundreds, one of those days I was calling person after person, asking the same three questions, trying to fill a role I could barely describe myself, let alone screen candidates for properly.\n\nIf someone had told me that day one of those calls would turn into one of the closest friendships of my life, I'd have laughed and said, \"Unlikely.\" I'd have been wrong, but I'd have said it with full confidence, which is usually how I'm wrong about most things.\n\nAnd then you answered.\n\nI don't remember every word of that call. I remember how it felt. There was confidence in your voice, not the loud kind trying to prove something, the quiet kind that comes from actually knowing what you're capable of. Underneath it, something else too. You wanted a chance. Not because you were running from where you were, but because you wanted to grow.\n\nSomewhere in the middle of it, almost as an aside, you mentioned you were on your way to a temple. You probably forgot you'd said it five minutes later.\n\nI didn't. People give themselves away in the smallest, most ordinary sentences. That one told me more than the résumé did."
  },
  {
    title: "Page 3",
    text: "Then came the interview, and I walked out and told Mansi, more or less, \"We should hire her.\" Simple. No overthinking, which, if you know how my brain usually works, is genuinely saying something. I tend to overanalyse decisions that don't matter, like which vendor to call first, and somehow skip straight past the ones that do. This was one of the rare times I got that order right.\n\nHere's a detail you don't know. You were my first hire after I joined Troovy. First real decision I made in that job, back when I was still finding my own footing, and somehow it turned out to be the best one I've made since. I thought I was hiring someone to help manage the work. What I actually found was someone who'd quietly become one of the people I trust most. Different things entirely. I didn't know it yet, sitting across the table from you, trying to look like I knew what I was doing. For the record, I did not know what I was doing. Nobody tells you that in your first real job. You just fake it convincingly enough that people stop asking.\n\nThe first few weeks, I told you what I expected from the role. You listened, then quietly exceeded all of it without making any noise about it, which is more than I can say for most people I've worked with, myself included on a bad day. The lab slowly started becoming yours. Everything had a place. People knew who to ask. Problems got solved before they became problems worth mentioning in a meeting, which, if you've sat through as many of my meetings as you have, you'll know is no small mercy.\n\nThat's one of my favourite things about you. You don't chase appreciation. You chase responsibility. And once you own something, everyone around you stops worrying, because they know it'll get done. For someone like me, that's an enormous relief. Talent's great. Reliability's priceless. You've always been reliable."
  },
  {
    title: "Page 4",
    text: "Somewhere between the professional conversations, we started talking about ordinary, unimportant things, which I've since learned is usually how the good stuff sneaks in. Nobody tells you that the real friendship starts in the five minutes before a meeting, not the meeting itself.\n\nYou mentioned once, very casually, that your family wanted you to marry a Marwari Baniya. My brain immediately produced the name of one unmarried Baniya I happened to know. Poor guy never found out he was under consideration for a role he had zero chance at. You rejected him before he'd even entered the story. After that, every time you pointed at some smart-looking guy, my job for the day was simple: tease you about it, without mercy. I don't remember half the names now. I remember laughing.\n\nThat's how most good friendships actually start, I think. Not one big moment. A hundred small, forgettable conversations that quietly become your favourite memories without asking permission first.\n\nOne evening we'd been fighting the HFSS Excel model for hours. That thing has personally aged me. By the time we stopped, we were both fried, so we stepped out and you suggested Laphing. I'd never even heard of it, which you found deeply amusing given how long I'd apparently lived without trying it.\n\nI honestly don't remember how it tasted. I only remember laughing. Which, now that I think about it, is exactly what friendship is supposed to feel like."
  },
  {
    title: "Page 5",
    text: "Here's something you may not fully know about me. I'm a core manufacturing guy. Machines, processes, efficiency, that's the language I understand instinctively. Quality was never my territory, and if you ask me to define a CAPA from memory even today, I will hesitate just long enough for you to notice. So hiring for that role wasn't just filling a seat, it was one of the harder calls I had to make. I needed someone I could actually rely on, someone who'd understand the work and understand me. Turns out I got lucky. Somewhere between reports, CAPAs, audits and daily chaos, you became the one person I never had to worry about. That kind of reliability is rare, and I don't think I've thanked you enough for it. It's a strange thing, watching someone from a completely different discipline end up understanding your job better than people who share your own. I still tease you that Quality people overcomplicate things that manufacturing would fix in an hour. You still tell me manufacturing people would ship a fire hazard if it hit the numbers. We're both a little bit right, which is probably why the arguments never actually go anywhere and somehow still end in laughing.\n\nThere was a stretch neither of us will forget easily. Quality had gotten difficult, and for the first time in a while, I started questioning myself. Was I actually good enough for this. Those thoughts get loud fast when you're already tired, louder still when you're the one people expect to have the answers, and I am, on paper, supposed to have most of them.\n\nYou probably never realised how much your presence helped, not because you solved anything, but because you kept, quietly, reminding me that I could. Sometimes that's the entire job of a friend. Not fixing the problem. Just sitting near it with you until it feels smaller.\n\nThen one day you called and told me Mansi had spoken to you, asked about me, my work, what kind of person I was, and you backed me completely without me ever asking. Told me almost as an afterthought too, days later, like it wasn't a big deal. It was. Standing up for someone in front of them is easy. Standing up for them when they're not even in the room, that's character. And as if that wasn't enough, you started quietly asking around about opportunities for me too. Nothing to gain from it. You did it anyway. I still don't know how to properly say thank you for the kind of confidence that just lets a person get through a"
  },
  {
    title: "Page 6",
    text: "Tuesday. So I'm saying it now, in writing, where it counts more apparently. Thank you.\n\nI keep noticing, writing all this down, how much of this letter is just a list of ordinary Tuesdays. That's probably the point. Nobody warns you that the best friendships are made of the boring days, not the dramatic ones."
  },
  {
    title: "Page 7",
    text: "Long before we ever boarded a flight together, I'd already decided you should be the one to experience flying first. You'd mentioned, casually, that you'd never been on a plane, and that you were a little scared of it, which, if I'm honest, sounded exactly like something you'd say. Excited and overthinking it, simultaneously, a very you combination.\n\nSo when the chance came up for Delhi, I told Mansi to send you instead of me. Life had other plans. Instead of sending someone else with you, it sent me. I'm glad it ignored mine, and I don't say that about most of my own plans.\n\nPeople usually remember flights for the destination. I remember that one for the conversation. Somewhere above the clouds, the office disappeared, designations disappeared, targets disappeared, and for once we weren't discussing work. Just life, families, dreams, the kind of things people don't usually tell colleagues, or even most friends. I don't remember the altitude. I remember that somewhere between take-off and landing, I found something I wasn't even looking for. A person I could actually talk to without filtering, without worrying how it'd be read. You don't realise how rare that is until you find it, and by then you've usually already spent years collecting the kind of acquaintances who only ever get the polished version of you.\n\nYou became the keeper of a few stories I'd never planned on telling anyone, and you've protected every one of them since. Not once has any of it found its way back to me through someone else. That's not a small thing. Thank you for being one of the safest places my words have ever had."
  },
  {
    title: "Page 8",
    text: "Somewhere on that same trip I discovered you had the exact same taste in old songs as me, which is roughly when we both got a little suspicious of each other. You'd play something, clearly hoping I hadn't heard it. I didn't have the heart to disappoint you as often as I did, and disappointed you anyway, every time, because apparently my heart recovers quickly.\n\nThen came Shah Rukh Khan, and that's when the coincidence stopped being funny. Same era, same old films, same hopelessly romantic classics, none of it planned. There was one song I spent the entire trip trying to name. My brain finally cooperated about four seconds before I dropped you at your PG. Typical. After that, Instagram quietly turned into a running competition neither of us agreed to start. You'd send a song hoping to catch me off guard. I'd disappoint you. I'd send one back. Neither of us ever really won, which was probably the best possible outcome, because the game never had to end.\n\nWe never became close because of one big moment. There wasn't a single day I thought, from today, she's my best friend. Believe me, I would remember a day like that, I remember far less important things with alarming precision. It happened the way the good things usually do. Quietly. One song, one lunch, one bad joke at a time, until I noticed this person had simply become part of my everyday life, and if you didn't show up, something felt incomplete. Not because I depended on you. Because I'd gotten used to sharing the ordinary parts of life with someone, which turns out to be rarer than it sounds, and a lot harder to replace than people assume."
  },
  {
    title: "Page 9",
    text: "One of my favourite things about us is how alike we are. Not identical, just similar where it matters. We're both overthinkers, unfortunately, and between the two of us we've probably solved problems that never even existed. If overthinking were an Olympic sport, we'd both medal, and then spend a week overthinking whether we deserved it. But somehow, instead of exhausting each other, we understand each other. Half the time I don't even have to explain why something's bothering me. You already know. Works the other way too. There's something comforting about someone understanding your silence almost as well as your words.\n\nSmall memory I keep coming back to, more than its size probably warrants. Terrible headache one day. Don't even remember mentioning it. I was just looking for you, and before I could say a word, you were already walking towards me, tablet in hand, like you'd read my mind. Never asked how you knew. Didn't surprise me either. Exactly the kind of thing you'd do. You notice people. Not because anyone asks you to. You just do, quietly, without turning it into a moment.\n\nThen there's the lunch thing. Several lunch things, honestly, spread across enough months I've stopped being able to tell them apart. Told individually they'd sound like nothing. That's it? Yes, that's it. Friendships aren't built on the big gestures. They're built on the small ones, repeated, with nobody keeping score. Days I forgot to order food because work had eaten my brain, you'd already ordered mine. You wait for me before eating, even starving, because you know if you go ahead I'll end up eating alone much later, staring at a screen, forgetting food exists. You've probably never thought twice about it. I have, usually while eating whatever you ordered for me, feeling mildly guilty and extremely well fed."
  },
  {
    title: "Page 10",
    text: "You have this habit of remembering things most people would forget. That I can't stand strong smells. Conversations from weeks ago I've long since dropped. Things I mention once, in passing, and forget I ever said, until you bring them up later, at exactly the right moment, usually when I've least prepared an answer. I've genuinely wondered if you keep secret notes somewhere. I have no better explanation, and I've tried to think of one.\n\nPeople think listening is about hearing words. It isn't. Listening is remembering them later, long after the conversation's ended, when there's nothing left to gain from remembering. I still haven't fully figured out whether listening is your superpower or your biggest weakness, given how much of other people's nonsense you end up carrying around. Either way, you've somehow managed to listen to me for this long, which honestly deserves an award of some kind. I'd nominate you myself if I knew who to send the form to."
  },
  {
    title: "Page 11",
    text: "To the Best Listener I Know,\nthe Keeper of My Secrets,\nand one of the Kindest Souls I have ever met.\n\nThat's a rare thing to be. Please don't ever lose it.\n\nI keep pausing on this next part, not because I don't know what to say, but because I don't know why I still remember it in this much detail. Some memories just stick harder than others for no good reason. This is one of them."
  },
  {
    title: "Page 12",
    text: "I won't forget my last birthday any time soon. Not the cake, not the celebrations, not even the wishes. A handful of tiny Naruto figures did it. Out of every possible gift in a city full of shops selling the same candles and the same mugs saying the same things, you found something unmistakably me. That wasn't a present. That was proof you'd been paying attention the whole time, filing away some comment I made once and forgot within the hour. I still don't know when you even noted that down.\n\nThen the chocolate. The one someone important to you had given you. You could've kept it easily, no one would've blinked. Instead you split it and handed half to me, mid-conversation, like it was nothing. You probably think of it as just chocolate. I don't. That's trust, and the quiet way you make people feel included without ever making a production of it.\n\nI've thought about that chocolate more than a grown man probably should. Not the taste. The handing over of it, without a second thought. That's the part that stuck.\n\nOne day, scrolling Instagram like you do, you sent me a reel. Nothing dramatic. Some fifteen-second thing I don't even remember, except the caption, which happened to say I was your best friend. You probably sent it, smiled, moved on with your day.\n\nI didn't. I went back and watched it again later, which I'll admit is a slightly unhinged thing to do with a reel. But people like us don't use words like that lightly. We overthink everything, hesitate before saying things we mean, take forever to actually trust someone, let alone say it out loud in a caption meant for no one in particular. That's exactly why it landed the way it did. I still haven't told you I rewatched it. Consider this letter the confession."
  },
  {
    title: "Page 13",
    text: "Here's something I don't think I've properly said. You've quietly changed me. Not through lectures, through repetition. Go home more. Spend time with your parents. Play with Aarav. Don't let work eat your whole life. Ordinary sentences, at first. Then one day I noticed I'd actually started listening to them. Talking to you has become a strange kind of therapy, the kind without appointments, that happens over lunch or a stupid meme. You have no idea how much those conversations have helped. Thank you for reminding me there's a life outside deadlines, and that sometimes all a person needs is someone telling them to go home.\n\nFunny thing to write in a letter about friendship, a paragraph about faith, but stick with me, because it's one of the parts I actually care most about getting right.\n\nRajkot gave me something I didn't expect. Not just another work trip. Hanuman Ji, then ISKCON, then sitting afterwards talking about life over food that tasted better simply because of who I was sitting across from. I noticed something about you there. You never force your beliefs on anyone. You just live them, quietly, which is probably exactly why they're contagious. I don't know if you'll agree, but somewhere on that trip, I started believing again. Not because anyone argued me into it. Because watching your faith made me quietly rediscover mine. Some people bring happiness into your life. You brought back faith. I still don't fully know how to thank someone for that, so I've mostly just been doing it badly, a little at a time, hoping it eventually adds up."
  },
  {
    title: "Page 14",
    text: "There's something I've never told you, and your birthday feels like the day for it. You once mentioned you weren't ready for marriage yet, not that you didn't want it, just not yet. I understood. Some things shouldn't be rushed.\n\nA few weeks later I was in Gujarat. Visited Somnath, then Dwarka, the kind of places people go to ask for something big. Success, health, a promotion, whatever it is people usually queue up for. I didn't ask for any of that. I asked for one thing, that Kanha Ji give you the time you need. That whenever that chapter begins, it begins because you're ready, not because anyone else is waiting. You never knew I prayed for you. Wasn't planning on telling you either, but birthdays are for honesty, apparently, at least the way I write them. Trust Him a little more. That's advice from a Yaduvanshi, for what it's worth, and I realise that's a fairly niche qualification to be handing out advice on."
  },
  {
    title: "Page 15",
    text: "I want to clear something up, while we're being honest. I know I tease you, relentlessly, about the people you find interesting, and I know teasing can look a lot like disapproval from the outside, especially from someone as loud about it as I am. It isn't. Teasing's always been my language. Respect's always been the intention underneath it, even if the delivery needs work.\n\nI've always respected your choices, and always will, because they're yours to make, not mine to judge. So if there's ever a day you need someone to help you meet him, cover for you, or just sit and listen while you overthink the whole thing for the hundredth time, at whatever ungodly hour you decide to call, I'll be there. That's what friends are for. Not deciding your happiness. Helping you get to it, and occasionally providing a convenient alibi along the way.\n\nI still owe you an apology for how many shows you've ruined my schedule with. I'd finally escape one series and another recommendation would quietly land in my inbox before I'd even finished the credits. Annoyingly, it was almost always good, which meant I had no real grounds to complain, only the illusion of one, which I nonetheless made full use of, loudly and often."
  },
  {
    title: "Page 16",
    text: "One character from all of it stuck with both of us. Rishi Singh Shekhawat. We talked about him more than either of us probably intended to, his honesty, his loyalty, the way he stood by the people he cared about. Genuinely one of the better-written characters either of us had come across, which is saying something given how many hours we've collectively spent complaining about writing quality in shows we still finish anyway. But there was one thing he did that never sat right with either of us. He gave away his best friend's secrets.\n\nWe joked about it for weeks after. \"Don't be a Rishi,\" became a running line between us, thrown in whenever one of us said something the other clearly shouldn't repeat. Still is, actually. It stayed a joke, and I'd like it to stay one. But somewhere underneath the joke, I made myself an actual promise. Your conversations stay yours. Your secrets stay yours. Your fears, your overthinking, your terrible jokes, everything you've ever handed me for safekeeping, all of it stays exactly where it belongs. With me. I don't plan on ever becoming that version of Rishi, even as a bit."
  },
  {
    title: "Page 17",
    text: "Which brings me to the part of this letter I've rewritten more times than the rest of it combined, because I wanted to get it right, and because I know if I get this part wrong, nothing else in this letter really matters.\n\nWhat we've built is rare. Trust. Comfort. The freedom to say anything without being judged for it, and the freedom to say nothing at all. I don't want to wrap this one in a joke the way I usually would, so I'll just say it plainly, once, and mean every word of it."
  },
  {
    title: "Page 18",
    text: "I will never misuse the trust you've placed in me. I will never become a reason you feel uncomfortable. I will never let this friendship turn into something you need to protect yourself from.\n\nThose are just words on a page, and words are cheap from someone who talks as much as I do. So take it from everything before this page instead. Every secret that stayed a secret. Every door I never once tried to open that wasn't mine to open. That isn't a promise I'm making today. It's one I've already been keeping, quietly, since the day you decided I was worth trusting. I intend to keep keeping it, for exactly as long as you'll let me, no conditions attached.\n\nI know this is the part of the letter where I'm supposed to say something clever to lighten the mood again. I'm choosing not to, just this once. Some things are allowed to just sit there, plainly, without a joke standing guard over them.\n\nSo, a few wishes, before I let you go actually enjoy your birthday, because I did promise myself I'd wrap this up before it turned into a second letter."
  },
  {
    title: "Page 19",
    text: "I hope you never lose the part of you that notices people, that somehow knows when someone isn't okay even when they insist they are. I hope you keep writing letters, because they're genuinely beautiful, and because one of yours is the reason this one exists. I hope you worry a little less over the small things. Easier said than done, I know, for a fellow overthinker. But life's too short to spend so much of it bracing for problems that haven't even happened yet.\n\nSmile more. Laugh louder. Keep making reels I'll pretend to find embarrassing while secretly rewatching them. Keep the recommendations coming, I clearly have no self-control anyway, and pretending otherwise at this point would just be dishonest. Keep sending old songs, you still haven't managed to surprise me, for the record, and I intend to keep it that way out of pure stubbornness. Keep believing in Kanha Ji, because watching you do that helped me believe a little more too.\n\nThank you for reminding me there's always time for parents, for Aarav, for family and faith, and never quite enough time for the people who actually matter. And someday, when I finally finish that book on friendship I keep threatening to write, currently existing only as a title and a great deal of procrastination, you get the first copy. Signed. Free of charge. No negotiations, though I imagine you'll try anyway.\n\nI don't know where life takes us from here. Different cities, maybe, different responsibilities, busier years than this one. That's fine. Real friendships aren't measured by how often you talk. They're measured by knowing one message is enough when it actually matters. So whenever you need someone, to celebrate, to overthink, to complain, to trade another old song, or just to sit in silence, you know where to find your Elderly Person."
  },
  {
    title: "Page 20",
    text: "I paused writing here for a bit, actually, longer than I'd like to admit for a man who claims to always have something to say. Partly because I wasn't sure how to end this without it turning into something heavier than I wanted it to be. This letter was never supposed to make you cry. It was supposed to make you smile, maybe roll your eyes once or twice at how long I made it, and then go back to your birthday feeling a little more appreciated than you did an hour ago. So let me try to land it that way.\n\nI hope Kanha Ji gives you a life kinder than your heart already is. I hope every dream you're carrying finds you exactly on time. And I hope you never stop being exactly who you are, because this world could use a lot more people who notice, who remember, who quietly care without needing anyone to see them doing it.\n\nIf someone asks me years from now what the best thing I found at Troovy was, I won't say a project or a promotion. I won't even pretend to think about it. I'll just smile and say: a friend.\n\nHappy Birthday. Keep being you. I wouldn't trade this particular chaos for anything, and believe me, as someone who has spent an entire career trying to reduce variability in a manufacturing line, that is the highest compliment I know how to give.\n\nSome friendships you fall into. Ours I got to watch happen, one ordinary Tuesday at a time, and I wouldn't have wanted to miss a single one of them. Not the headaches, not the lunches, not the terrible song recommendations, none of it. Even the parts that felt small at the time turned out, looking back, to be most of the letter.\n\nIf you're reading this years from now, older, busier, maybe in a different city entirely, I hope it still sounds like me. And I hope some version of us, whatever that looks like by then, is still trading old songs neither of us ever really wins."
  },
  {
    title: "Page 21",
    text: "— Elderly Person"
  },
  {
    title: "The Poem",
    text: "THE POEM\n\nSome friendships announce themselves.\nOurs introduced itself quietly —\na résumé in a stack of hundreds,\na sentence about a temple\nyou probably forgot you said.\n\nNobody plans the small things\nthat end up mattering most:\na tablet pressed into a hand\nbefore a word was spoken,\nan old song sent just to see if I'd notice,\na question that wants nothing back —\nhave you eaten yet?\n\nTrust doesn't arrive all at once.\nIt gathers, the way evidence does —\none kept secret at a time,\none lunch you waited for,\none truth you let me carry\nwithout once asking for it back.\n\nSo here is what I wish you,\nplainly, the way you'd say it to me:\nstay exactly this open.\nLet your faith stay bigger than your fear.\nKeep noticing what everyone else walks past.\n\nMay Kanha Ji walk a little ahead of you,\nclearing roads you haven't reached yet.\nAnd on the days that feel uncertain,\nremember this much —"
  },
  {
    title: "The Poem",
    text: "some friendships aren't measured in years.\nThey're measured in who kept showing up.\n\nThank you for showing up in mine.\n\n— Elderly Person"
  }
];